//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pdf.Client.ProcessXmlHandler {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gemikro.rs", ConfigurationName="ProcessXmlHandler.ProcessXmlHandlerSoap")]
    public interface ProcessXmlHandlerSoap {
        
        // CODEGEN: Generating message contract since element name request_string from namespace http://www.gemikro.rs is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gemikro.rs/ProcessRequestJson", ReplyAction="*")]
        Pdf.Client.ProcessXmlHandler.ProcessRequestJsonResponse ProcessRequestJson(Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gemikro.rs/ProcessRequestJson", ReplyAction="*")]
        System.Threading.Tasks.Task<Pdf.Client.ProcessXmlHandler.ProcessRequestJsonResponse> ProcessRequestJsonAsync(Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequest request);
        
        // CODEGEN: Generating message contract since element name request_string from namespace http://www.gemikro.rs is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gemikro.rs/ProcessRequest", ReplyAction="*")]
        Pdf.Client.ProcessXmlHandler.ProcessRequestResponse ProcessRequest(Pdf.Client.ProcessXmlHandler.ProcessRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gemikro.rs/ProcessRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Pdf.Client.ProcessXmlHandler.ProcessRequestResponse> ProcessRequestAsync(Pdf.Client.ProcessXmlHandler.ProcessRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessRequestJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessRequestJson", Namespace="http://www.gemikro.rs", Order=0)]
        public Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequestBody Body;
        
        public ProcessRequestJsonRequest() {
        }
        
        public ProcessRequestJsonRequest(Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gemikro.rs")]
    public partial class ProcessRequestJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request_string;
        
        public ProcessRequestJsonRequestBody() {
        }
        
        public ProcessRequestJsonRequestBody(string request_string) {
            this.request_string = request_string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessRequestJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessRequestJsonResponse", Namespace="http://www.gemikro.rs", Order=0)]
        public Pdf.Client.ProcessXmlHandler.ProcessRequestJsonResponseBody Body;
        
        public ProcessRequestJsonResponse() {
        }
        
        public ProcessRequestJsonResponse(Pdf.Client.ProcessXmlHandler.ProcessRequestJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gemikro.rs")]
    public partial class ProcessRequestJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessRequestJsonResult;
        
        public ProcessRequestJsonResponseBody() {
        }
        
        public ProcessRequestJsonResponseBody(string ProcessRequestJsonResult) {
            this.ProcessRequestJsonResult = ProcessRequestJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessRequest", Namespace="http://www.gemikro.rs", Order=0)]
        public Pdf.Client.ProcessXmlHandler.ProcessRequestRequestBody Body;
        
        public ProcessRequestRequest() {
        }
        
        public ProcessRequestRequest(Pdf.Client.ProcessXmlHandler.ProcessRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gemikro.rs")]
    public partial class ProcessRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request_string;
        
        public ProcessRequestRequestBody() {
        }
        
        public ProcessRequestRequestBody(string request_string) {
            this.request_string = request_string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessRequestResponse", Namespace="http://www.gemikro.rs", Order=0)]
        public Pdf.Client.ProcessXmlHandler.ProcessRequestResponseBody Body;
        
        public ProcessRequestResponse() {
        }
        
        public ProcessRequestResponse(Pdf.Client.ProcessXmlHandler.ProcessRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gemikro.rs")]
    public partial class ProcessRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessRequestResult;
        
        public ProcessRequestResponseBody() {
        }
        
        public ProcessRequestResponseBody(string ProcessRequestResult) {
            this.ProcessRequestResult = ProcessRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcessXmlHandlerSoapChannel : Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessXmlHandlerSoapClient : System.ServiceModel.ClientBase<Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap>, Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap {
        
        public ProcessXmlHandlerSoapClient() {
        }
        
        public ProcessXmlHandlerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessXmlHandlerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessXmlHandlerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessXmlHandlerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pdf.Client.ProcessXmlHandler.ProcessRequestJsonResponse Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap.ProcessRequestJson(Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequest request) {
            return base.Channel.ProcessRequestJson(request);
        }
        
        public string ProcessRequestJson(string request_string) {
            Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequest inValue = new Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequest();
            inValue.Body = new Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequestBody();
            inValue.Body.request_string = request_string;
            Pdf.Client.ProcessXmlHandler.ProcessRequestJsonResponse retVal = ((Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap)(this)).ProcessRequestJson(inValue);
            return retVal.Body.ProcessRequestJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pdf.Client.ProcessXmlHandler.ProcessRequestJsonResponse> Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap.ProcessRequestJsonAsync(Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequest request) {
            return base.Channel.ProcessRequestJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pdf.Client.ProcessXmlHandler.ProcessRequestJsonResponse> ProcessRequestJsonAsync(string request_string) {
            Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequest inValue = new Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequest();
            inValue.Body = new Pdf.Client.ProcessXmlHandler.ProcessRequestJsonRequestBody();
            inValue.Body.request_string = request_string;
            return ((Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap)(this)).ProcessRequestJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pdf.Client.ProcessXmlHandler.ProcessRequestResponse Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap.ProcessRequest(Pdf.Client.ProcessXmlHandler.ProcessRequestRequest request) {
            return base.Channel.ProcessRequest(request);
        }
        
        public string ProcessRequest(string request_string) {
            Pdf.Client.ProcessXmlHandler.ProcessRequestRequest inValue = new Pdf.Client.ProcessXmlHandler.ProcessRequestRequest();
            inValue.Body = new Pdf.Client.ProcessXmlHandler.ProcessRequestRequestBody();
            inValue.Body.request_string = request_string;
            Pdf.Client.ProcessXmlHandler.ProcessRequestResponse retVal = ((Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap)(this)).ProcessRequest(inValue);
            return retVal.Body.ProcessRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pdf.Client.ProcessXmlHandler.ProcessRequestResponse> Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap.ProcessRequestAsync(Pdf.Client.ProcessXmlHandler.ProcessRequestRequest request) {
            return base.Channel.ProcessRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pdf.Client.ProcessXmlHandler.ProcessRequestResponse> ProcessRequestAsync(string request_string) {
            Pdf.Client.ProcessXmlHandler.ProcessRequestRequest inValue = new Pdf.Client.ProcessXmlHandler.ProcessRequestRequest();
            inValue.Body = new Pdf.Client.ProcessXmlHandler.ProcessRequestRequestBody();
            inValue.Body.request_string = request_string;
            return ((Pdf.Client.ProcessXmlHandler.ProcessXmlHandlerSoap)(this)).ProcessRequestAsync(inValue);
        }
    }
}
